{{/* 
HUMAN TASKS:
1. Verify that an Ingress Controller (e.g., nginx-ingress, traefik) is installed in the cluster
2. Ensure TLS certificates are properly configured if using HTTPS
3. Review and configure any required Ingress annotations based on your Ingress Controller
4. Validate that DNS records are configured to point to the Ingress Controller's external IP/hostname
*/}}

{{/* Requirement Addressed: External Access Configuration - Configures external access to Spring Boot application endpoints */}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "spring-boot-app.fullname" . }}
  labels:
    {{- include "spring-boot-app.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{/* Main application endpoints */}}
          - path: {{ default "/" .path }}
            pathType: {{ default "Prefix" .pathType }}
            backend:
              service:
                name: {{ include "spring-boot-app.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
          {{/* Actuator endpoints if enabled */}}
          {{- if and $.Values.actuator.enabled .exposeActuator }}
          - path: {{ printf "%s/(.+)" $.Values.actuator.path }}
            pathType: {{ default "Prefix" .pathType }}
            backend:
              service:
                name: {{ include "spring-boot-app.fullname" $ }}
                port:
                  number: {{ $.Values.actuator.port }}
          {{- end }}
    {{- end }}
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- end }}