{{/* 
HUMAN TASKS:
1. Verify that all sensitive values are properly configured in a secure values file (not in the main values.yaml)
2. Ensure proper RBAC permissions are set up for accessing secrets
3. Review secret rotation and management policies
4. Configure proper encryption for secrets at rest in etcd
*/}}

{{/* Requirement Addressed: Spring Boot Application Security - Creates Kubernetes Secret for storing sensitive configuration */}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spring-boot-app.fullname" . }}-secret
  labels:
    {{- include "spring-boot-app.labels" . | nindent 4 }}
type: Opaque
data:
  {{/* Requirement Addressed: Application Configuration - Securely stores application properties */}}
  
  # Database credentials
  {{- if .Values.springApplication.database }}
  DB_URL: {{ .Values.springApplication.database.url | b64enc | quote }}
  DB_USERNAME: {{ .Values.springApplication.database.username | b64enc | quote }}
  DB_PASSWORD: {{ .Values.springApplication.database.password | b64enc | quote }}
  {{- end }}

  # Spring application properties
  SPRING_PROFILES_ACTIVE: {{ .Values.springApplication.profile | b64enc | quote }}
  SPRING_APPLICATION_VERSION: {{ .Values.springApplication.version | b64enc | quote }}

  # API keys and external service credentials
  {{- if .Values.springApplication.api }}
  {{- range $key, $value := .Values.springApplication.api.keys }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}

  # JWT/Security configuration
  {{- if .Values.springApplication.security }}
  {{- if .Values.springApplication.security.jwt }}
  JWT_SECRET: {{ .Values.springApplication.security.jwt.secret | b64enc | quote }}
  JWT_EXPIRATION: {{ .Values.springApplication.security.jwt.expiration | b64enc | quote }}
  {{- end }}
  {{- end }}

  # Actuator security credentials if authentication is enabled
  {{- if .Values.actuator.security }}
  {{- if .Values.actuator.security.credentials }}
  ACTUATOR_USERNAME: {{ .Values.actuator.security.credentials.username | b64enc | quote }}
  ACTUATOR_PASSWORD: {{ .Values.actuator.security.credentials.password | b64enc | quote }}
  {{- end }}
  {{- end }}

  # Additional application-specific secrets
  {{- if .Values.springApplication.additionalSecrets }}
  {{- range $key, $value := .Values.springApplication.additionalSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}